name: Build and Distribute
run-name: ${{ github.actor }} is building FileNinja
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    #runs-on: [self-hosted, linux, x64, gpu]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install FileNinja dependencies
        run: |
          python -m pip install .
      - name: Build FileNinja
        run: |
          python -m pip install .[build]
          pyinstaller src/file_ninja/main.py -n fini
      - name: Verify Build
        run: |
          if ! ./dist/fini/fini --help; then
            exit 1
          fi
      - name: Package FileNinja
        run: |
          ninja_version=$(cat VERSION)
          runner_os=$(echo "${{runner.os}}" | awk '{print tolower($0)}')
          runner_arch=$(echo "${{runner.arch}}" | awk '{print tolower($0)}')
          echo $ninja_version
          echo $runner_os
          echo $runner_arch
        env:
          ninja_version: ''
          runner_os: ''
          runner_arch: ''
